name: booking_demo
description: Demo app for bookings with Retrofit, Bloc, DI, and GoRouter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  go_router: ^14.2.0
  dio: ^5.7.0
  retrofit: ^4.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0

  collection: ^1.18.0

  url_strategy: ^0.3.0

  cupertino_icons: ^1.0.2
  sentry_flutter: ^8.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^9.7.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  mocktail: ^1.0.4
  coverage: ^1.11.0


flutter:
  uses-material-design: true

